name: sample
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - matplotlib
  - pandas
  - python=3.7
  - pip=18
  - plotly
  - seaborn
  - jupyter
  - jupyter_client
  - jupyter_console
  - notebook
  - numpy
  - pickleshare
  - pylint
  - scipy